#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=ff
bspc rule -a spotify desktop='^7' focu=on
bspc rule -a discord desktop='^3' focus=on
bspc rule -a zoom desktop='^3' focus=on
bspc rule -a obs desktop='^8' focus=on
bspc rule -a kdenlive desktop='^8' focus=on
bspc rule -a code desktop='^5' focus=on

. "${HOME/.cache/wal/colors.sh}"
# Border
bspc config focused_border_color        "#C97D54"
bspc config normal_border_color         "#9891B6"
bspc config active_border_color         "#fff"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
wal -i /home/astral/Pictures/Wallpapers -o wal -set &
wal -R

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

